### ISSUE TITLE
rdbs command

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#47]
getting an odd error.  hopefully I got the command right..I edited out the password

```
C:\clc>clc db create --instance-type mysql --external-id chrismysql --machine-config "cpu=2,memory=4,storage=15" --backup-retention-days 5 --users "name=chris,password=XXXX --data-center VA1
```

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/centurylinkcloud/clc-go-cli/model_validator.pretifyError(0xc0820d6dc0, 0x1d, 0x0, 0x0)
        /Users/ldmberman/.gvm/pkgsets/go1.4.2/centurylink/src/github.com/centurylinkcloud/clc-go-cli/model_validator/model_validator.go:100 +0x1e1
github.com/centurylinkcloud/clc-go-cli/model_validator.ValidateModel(0x7d2ee0, 0xc082066160, 0x0, 0x0)
        /Users/ldmberman/.gvm/pkgsets/go1.4.2/centurylink/src/github.com/centurylinkcloud/clc-go-cli/model_validator/model_validator.go:23 +0x1c7
main.Run(0xc082022010, 0xc, 0xc, 0x0, 0x0)
        /Users/ldmberman/Programming/clc-go-cli/cmd/clc/runner.go:90 +0xa76
main.main()
        /Users/ldmberman/Programming/clc-go-cli/cmd/clc/main.go:21 +0x1dd

goroutine 2 [runnable]:
runtime.forcegchelper()
        /Users/ldmberman/.gvm/gos/go1.4.2/src/runtime/proc.go:90
runtime.goexit()
        /Users/ldmberman/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /Users/ldmberman/.gvm/gos/go1.4.2/src/runtime/mgc0.go:82
runtime.goexit()
        /Users/ldmberman/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /Users/ldmberman/.gvm/gos/go1.4.2/src/runtime/malloc.go:712
runtime.goexit()
        /Users/ldmberman/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by ldmberman** [comment]
My bad, I've built the releases with the old dependencies.

I've updated the releases page with the new archives. Could you, please, give it another try?

There is no MacOS .pkg for now - I'll add it later today.

**Comment by chrislittle** [comment]
ok looks better but i still get

```
Error occured while sending request to API. Status code: 500.
```

I suspect I have the syntax wrong somewhere so i'll keep trying

**Comment by ldmberman** [comment]
@chrislittle I can help you troubleshooting this if you post some `--trace` output. Just don't forget to cover up the sensitive information.

**Comment by chrislittle** [comment]
I added the --trace to the end of the command but it didn't put out any more data

**Comment by ldmberman** [comment]
I don't see the second double quote here - `--users "name=chris,password=XXXX --data-center VA1`. It should be the cause of the problem.

**Comment by chrislittle** [comment]
it actually was not that.  i had that (scroll in github).  i missed a " at the end of password !!! DUH!
