### ISSUE TITLE
Integration Tests Fail

### ISSUE THREAD

**Issue by richardcase** [CenturyLinkCloud/clc-go-cli#70]
When running the integration tests there are numerous errors with tests. An example of the errors:

`2016/10/07 10:06:36 http: panic serving 127.0.0.1:35646: unexpected end of JSON input
goroutine 41 [running]:
net/http.(*conn).serve.func1(0xc8200daa80)
    /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x8f73c0, 0xc82031b5e0)
    /usr/local/go/src/runtime/panic.go:443 +0x4e9
main.(*runner).addHandlerBase.func1(0x7f4326bbe0f8, 0xc820318410, 0xc820162e00)
    /home/richard/Documents/Code/go/src/github.com/centurylinkcloud/clc-go-cli/integration_tests/runner.go:110 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc82031af40, 0x7f4326bbe0f8, 0xc820318410, 0xc820162e00)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82030d290, 0x7f4326bbe0f8, 0xc820318410, 0xc820162e00)
    /usr/local/go/src/net/http/server.go:1910 +0x17d
main.(*runner).addServeMux.func1(0x7f4326bbe0f8, 0xc820318410, 0xc820162e00)
    /home/richard/Documents/Code/go/src/github.com/centurylinkcloud/clc-go-cli/integration_tests/runner.go:50 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc8203ef1f0, 0x7f4326bbe0f8, 0xc820318410, 0xc820162e00)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82030d230, 0x7f4326bbe0f8, 0xc820318410, 0xc820162e00)
    /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc8202cf580, 0x7f4326bbe0f8, 0xc820318410, 0xc820162e00)
    /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8200daa80)
    /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2137 +0x44e
Result received: EOF
: EOF`

**Comment by richardcase** [comment]
I will fix this.

On investigation the error is from the request comparison:
```
err = r.addHandler(url, string(resExampleString), func(req string) error {
		return r.compareJson(string(contentExampleString), req)
})
```
Specifically the the comparison in the callback.  We need to handle the following for API definitions in api.json:
```
"ContentExample": null,
```

**Comment by richardcase** [comment]
Multiple issues encountered and fixed when trying to get the integration tests working.

**Comment by richardcase** [comment]
Mixed in v1.1.0-rc.1
